import requests


sample_products = [
    {"name": "Smartwatch X1", "description": "Water-resistant smartwatch with fitness tracking", "price": 249.99},
    {"name": "Wireless Earbuds Pro", "description": "Noise-canceling earbuds with 20-hour battery", "price": 129.99},
    {"name": "4K Ultra HD TV", "description": "55-inch LED TV with HDR and smart features", "price": 599.99},
    {"name": "Gaming Laptop Z", "description": "High-performance laptop with RTX graphics", "price": 1499.99},
    {"name": "Bluetooth Speaker Mini", "description": "Portable speaker with deep bass", "price": 49.99},
    {"name": "Smart Home Hub", "description": "Control all your smart devices seamlessly", "price": 89.99},
    {"name": "Electric Kettle 2L", "description": "Fast-boiling kettle with auto shut-off", "price": 39.99},
    {"name": "Robot Vacuum Cleaner", "description": "Smart vacuum with app control", "price": 299.99},
    {"name": "Air Purifier Pro", "description": "HEPA filter air purifier for large rooms", "price": 179.99},
    {"name": "Tablet S10", "description": "10-inch tablet with 128GB storage", "price": 399.99},
    {"name": "Wireless Mouse", "description": "Ergonomic mouse with long battery life", "price": 24.99},
    {"name": "Gaming Console Neo", "description": "Next-gen console with 4K gaming", "price": 499.99},
    {"name": "Smart Thermostat", "description": "Energy-saving thermostat with remote control", "price": 119.99},
    {"name": "Coffee Maker Deluxe", "description": "Programmable coffee machine with grinder", "price": 89.99},
    {"name": "Fitness Tracker Fit", "description": "Track steps, heart rate, and sleep", "price": 59.99},
    {"name": "Portable SSD 1TB", "description": "High-speed external storage drive", "price": 129.99},
    {"name": "Smart Light Bulb", "description": "Color-changing bulb with voice control", "price": 19.99},
    {"name": "Wireless Charger", "description": "Fast-charging pad for smartphones", "price": 29.99},
    {"name": "Noise-Canceling Headphones", "description": "Over-ear headphones with 30-hour battery", "price": 199.99},
    {"name": "Action Camera 4K", "description": "Waterproof camera for adventure recording", "price": 149.99},
    {"name": "Smart Doorbell", "description": "Video doorbell with motion detection", "price": 129.99},
    {"name": "Electric Toothbrush", "description": "Rechargeable toothbrush with multiple modes", "price": 49.99},
    {"name": "Mini Projector", "description": "Portable projector for home theater", "price": 249.99},
    {"name": "Wireless Keyboard", "description": "Slim keyboard with quiet keys", "price": 39.99},
    {"name": "Smart Scale", "description": "Track weight and body metrics via app", "price": 59.99},
    {"name": "Portable Power Bank", "description": "20000mAh power bank with fast charging", "price": 34.99},
    {"name": "Smart Speaker Echo", "description": "Voice-activated speaker with AI assistant", "price": 99.99},
    {"name": "Gaming Mouse", "description": "RGB gaming mouse with programmable buttons", "price": 44.99},
    {"name": "Smart Fridge", "description": "Wi-Fi-enabled refrigerator with touchscreen", "price": 1999.99},
    {"name": "Dash Cam HD", "description": "1080p dash camera with night vision", "price": 79.99},
    {"name": "Air Fryer 5L", "description": "Healthy cooking with rapid air technology", "price": 89.99},
    {"name": "Smart Lock", "description": "Keyless entry lock with app control", "price": 149.99},
    {"name": "Portable Monitor", "description": "15.6-inch USB-C portable display", "price": 199.99},
    {"name": "Wireless Router AX", "description": "Wi-Fi 6 router for high-speed internet", "price": 129.99},
    {"name": "Electric Scooter", "description": "Foldable scooter with 20-mile range", "price": 399.99},
    {"name": "Smart Watch Series 5", "description": "Advanced smartwatch with ECG monitor", "price": 349.99},
    {"name": "Blender Pro", "description": "High-power blender for smoothies and soups", "price": 69.99},
    {"name": "Smart Plug", "description": "Wi-Fi-enabled plug for home automation", "price": 19.99},
    {"name": "VR Headset", "description": "Immersive virtual reality headset", "price": 299.99},
    {"name": "Cordless Vacuum", "description": "Lightweight vacuum with strong suction", "price": 179.99},
    {"name": "Smart Camera", "description": "Indoor security camera with 2-way audio", "price": 69.99},
    {"name": "Electric Grill", "description": "Indoor grill with adjustable temperature", "price": 99.99},
    {"name": "Wireless Earphones", "description": "True wireless earphones with charging case", "price": 79.99},
    {"name": "Smart Fan", "description": "App-controlled fan with oscillation", "price": 89.99},
    {"name": "Mini Fridge", "description": "Compact refrigerator for dorms or offices", "price": 129.99},
    {"name": "Gaming Chair", "description": "Ergonomic chair with lumbar support", "price": 199.99},
    {"name": "Smart Oven", "description": "Wi-Fi-enabled oven with recipe app", "price": 299.99},
    {"name": "Portable Speaker", "description": "Waterproof speaker with 15-hour battery", "price": 59.99},
    {"name": "Smart Glasses", "description": "Augmented reality glasses with audio", "price": 499.99},
    {"name": "Electric Blanket", "description": "Heated blanket with multiple settings", "price": 79.99},
    {"name": "Smart Kettle", "description": "Wi-Fi kettle with temperature control", "price": 69.99},
    {"name": "Webcam HD", "description": "1080p webcam with built-in microphone", "price": 49.99},
    {"name": "Smart Alarm Clock", "description": "Clock with sunrise simulation", "price": 39.99},
    {"name": "Noise Machine", "description": "White noise machine for better sleep", "price": 29.99},
    {"name": "Smart Humidifier", "description": "App-controlled humidifier for home", "price": 79.99},
    {"name": "Fitness Bike", "description": "Stationary bike with digital display", "price": 349.99},
    {"name": "Smart Mirror", "description": "Interactive mirror with fitness coaching", "price": 999.99},
    {"name": "Portable AC Unit", "description": "Compact air conditioner for small spaces", "price": 299.99},
    {"name": "Smart Diffuser", "description": "Aromatherapy diffuser with app control", "price": 49.99},
    {"name": "Gaming Monitor", "description": "27-inch 144Hz gaming monitor", "price": 249.99},
    {"name": "Smart Toaster", "description": "Wi-Fi-enabled toaster with custom settings", "price": 59.99},
    {"name": "Wireless Gamepad", "description": "Controller for PC and console gaming", "price": 39.99},
    {"name": "Smart Blinds", "description": "Motorized blinds with remote control", "price": 149.99},
    {"name": "Portable Heater", "description": "Compact heater with safety features", "price": 69.99},
    {"name": "Smart Water Bottle", "description": "Tracks hydration with app integration", "price": 29.99},
    {"name": "Mini Drone", "description": "Compact drone with HD camera", "price": 99.99},
    {"name": "Smart Lamp", "description": "Adjustable desk lamp with color modes", "price": 49.99},
    {"name": "Electric Shaver", "description": "Cordless shaver with precision blades", "price": 79.99},
    {"name": "Smart Pet Feeder", "description": "Automatic pet feeder with app control", "price": 129.99},
    {"name": "Noise-Canceling Earbuds", "description": "Compact earbuds with ANC", "price": 99.99},
    {"name": "Smart Coffee Grinder", "description": "Precision grinder with digital settings", "price": 89.99},
    {"name": "Portable Projector", "description": "Mini projector for outdoor movies", "price": 199.99},
    {"name": "Smart Thermometer", "description": "Digital thermometer with app tracking", "price": 39.99},
    {"name": "Electric Skateboard", "description": "High-speed board with remote control", "price": 499.99},
    {"name": "Smart Air Conditioner", "description": "Wi-Fi-enabled AC for smart homes", "price": 399.99},
    {"name": "Gaming Keyboard", "description": "Mechanical keyboard with RGB lighting", "price": 89.99},
    {"name": "Smart Smoke Detector", "description": "Wi-Fi-enabled smoke and CO detector", "price": 79.99},
    {"name": "Portable Battery Charger", "description": "10000mAh charger with USB-C", "price": 24.99},
    {"name": "Smart Ceiling Fan", "description": "Fan with voice and app control", "price": 149.99},
    {"name": "Mini Blender", "description": "Portable blender for smoothies on the go", "price": 34.99},
    {"name": "Smart Fitness Tracker", "description": "Advanced tracker with GPS", "price": 79.99},
    {"name": "Wireless Presenter", "description": "Laser pointer with slide control", "price": 19.99},
    {"name": "Smart Door Sensor", "description": "Security sensor with app alerts", "price": 29.99},
    {"name": "Electric Pressure Cooker", "description": "Multi-function cooker with presets", "price": 99.99},
    {"name": "Smart Light Strip", "description": "Color-changing LED strip with app", "price": 39.99},
    {"name": "Portable Karaoke Machine", "description": "Wireless karaoke with microphone", "price": 69.99},
    {"name": "Smart Sprinkler", "description": "Wi-Fi-enabled sprinkler for lawns", "price": 129.99},
    {"name": "Fitness Smart Scale", "description": "Body composition scale with app", "price": 59.99},
    {"name": "Smart Wall Outlet", "description": "Wi-Fi-enabled outlet for automation", "price": 34.99},
    {"name": "Mini Air Purifier", "description": "Compact purifier for small spaces", "price": 49.99},
    {"name": "Smart Bike Lock", "description": "GPS-enabled lock with app control", "price": 89.99},
    {"name": "Portable Espresso Maker", "description": "Handheld coffee maker for travel", "price": 59.99},
    {"name": "Smart Pet Camera", "description": "Camera with treat dispenser and app", "price": 129.99},
    {"name": "Wireless Trackpad", "description": "Multi-touch trackpad for laptops", "price": 49.99},
    {"name": "Smart Garage Opener", "description": "Wi-Fi-enabled garage door controller", "price": 99.99},
    {"name": "Electric Wine Opener", "description": "Rechargeable opener with foil cutter", "price": 29.99},
    {"name": "Smart Baby Monitor", "description": "HD camera with temperature sensor", "price": 149.99}
]

def insert_sample_products():
    token = '57ef3ed0007056f1ceaf9294f858076894eaa8bd' #admin token
    headers = {
        'Content-Type': 'application/json',
        'Authorization': f'Token {token}'
    }
    url = 'http://127.0.0.1:8000/api/products/'
    for product in sample_products:
        response = requests.post(url, json=product, headers=headers)
        print(response.json())

if __name__ == "__main__":
    insert_sample_products()
